# Generated by Django 5.2.3 on 2025-07-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_galleryimage_promotionalbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalbanner',
            name='height',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='width',
            field=models.PositiveIntegerField(default=1200),
        ),
    ]
