# Generated by Django 5.2.3 on 2025-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_promotionalbanner_height_promotionalbanner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_banners/')),
                ('width', models.PositiveIntegerField(default=1200)),
                ('height', models.PositiveIntegerField(default=400)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
